language: ruby

node_js:
  - 8.11.2

rvm:
  - 2.4.0

services:
  - redis-server

cache:
  bundler: true
  directories:
    - ~/.npm
    - node_modules

install:
  - bundle install && npm install

script:
  - npm run ci
