before_install:
  - rvm install "ruby-2.4.0"
  - rvm use 2.4.0
  - gem install bundler
  - bundle install
node_js:
  - 8.10.0
cache:
  directories:
    - ~/.npm
install:
  - npm install
script:
  - npm run test
