language: ruby

node_js:
  - 10.15.2

rvm:
  - 2.4.0

services:
  - redis-server

cache:
  yarn: true
  bundler: true
  directories:
    - node_modules

install:
  - bundle install && yarn install

script:
  - yarn ci
