language: ruby

node_js:
  - 8.10.0

rvm:
  - 2.4.0

cache:
  bundler: true
  directories:
    - ~/.npm
    - node_modules

install:
  - bundle install && npm install

before_script:
  - npm run prod-server -- --silent

script:
  - npm run ci
