name: CI

on: [push]

jobs:
  cypress-run:
    name: e2e tests
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node: [12.16.2]
    steps:
      - name: Setup Node
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node }}
      - run: node -v
      - name: Checkout
        uses: actions/checkout@v1
      - name: Cypress run
        uses: cypress-io/github-action@v2
        with:
          build: yarn build
          start: yarn start 3000
          wait-on: 'http://localhost:3000'
