name: CI

on:
  push:
    branches-ignore:
      - master

jobs:
  lint:
    name: lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup Node
        uses: actions/setup-node@v1
        with:
          node-version: '12.16.2'
      - name: Install modules
        run: yarn
      - name: Run ESLint
        run: yarn lint
  cypress-run:
    name: e2e tests
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        containers: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]
    steps:
      - name: Setup Node
        uses: actions/setup-node@v1
        with:
          node-version: '12.16.2'
      - run: node -v
      - name: Checkout
        uses: actions/checkout@v1
      - name: Cypress run
        uses: cypress-io/github-action@v2
        with:
          build: yarn install
          start: yarn dev
          group: 'Integration tests'
          record: true
          parallel: true
          wait-on-timeout: 120
          wait-on: 'http://localhost:3000'
        env:
          CYPRESS_RECORD_KEY: ${{ secrets.GFW_CYPRESS_KEY }}
