name: CI

on: [push]

jobs:
  lint:
    name: lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup Node
        uses: actions/setup-node@v1
        with:
          node-version: '12.16.2'
      - name: Install modules
        run: yarn
      - name: Run ESLint
        run: yarn lint
  cypress-run:
    name: e2e tests
    runs-on: ubuntu-latest
    strategy:
      # when one test fails, DO NOT cancel the other
      # containers, because this will kill Cypress processes
      # leaving the Dashboard hanging ...
      # https://github.com/cypress-io/github-action/issues/48
      fail-fast: false
      matrix:
        # run 3 copies of the current job in parallel
        containers: [1, 2, 3]
    steps:
      - name: Setup Node
        uses: actions/setup-node@v1
        with:
          node-version: '12.16.2'
      - run: node -v
      - name: Checkout
        uses: actions/checkout@v1
      - name: Cypress run
        uses: cypress-io/github-action@v2
        with:
          record: true
          parallel: true
          group: 'E2e tests'
          build: yarn build
          start: yarn start 3000
          wait-on: 'http://localhost:3000'
